stages:
  - build
  - deploy

variables:
  IMAGE_NAME: gribocheksan/hello-world-app:latest

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker pull $IMAGE_NAME || true

build_image:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
  artifacts:
    paths:
      - Dockerfile
      - main.go
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker run -d -p 8080:8080 $IMAGE_NAME
  only:
    - main