image: latest

services:
  - name: docker:20.10.14-dind
    alias: docker
    command: ["--tls=false"]

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: "gribocheksan/hello-world-app:latest"
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

build_image:
  stage: build
  script:
    - docker info  
    - docker build -t $IMAGE_NAME .
  artifacts:
    paths:
      - Dockerfile
      - main.go
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker run -d -p 8080:8080 $IMAGE_NAME
  only:
    - main