stages:
  - build
  - deploy

variables:
  IMAGE_NAME: your_dockerhub_username/sibit_test
  DOCKER_HOST: tcp://docker:2375/

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

build_image:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
  artifacts:
    paths:
      - Dockerfile
      - main.go
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker run -d -p 8080:8080 $IMAGE_NAME
  only:
    - main