stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t my-app:latest .
  only:
    - main